### PR TITLE
Regenerate the bindings with Servo's bindgen.

### LINKED ISSUE #47: FT_Bitmap row/width are unsigned
The documentation lists them as being `unsigned int`: https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_Bitmap

The binding code currently uses `i32`. Is this by design?

### PR DESCRIPTION
**Pull request by emilio**
r? @jdm 

Don't merge yet, since I guess quite a few crates will need to be updated, and I don't have time to do so right now (help would be appreciated!).

@kvark, I think this fixes #47.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-freetype/48)

### CODE REVIEW

**Comment by emilio** [comment]
Ok, this is ready for review, r? @jdm

**Comment by kvark** [comment]
Thanks @emilio !
I don't think it will break other crates, since you bumped the minor version, so it should be safe to land.

**Comment by jdm** [comment]
@bors-servo: r+
It's nice to modernize this. Thanks!

**Comment by kvark** [comment]
@SimonSapin could you publish the new version please?

**Comment by emilio** [comment]
I published it right now.

**Pull request merged**
